[build]
  command = "yarn build"
  functions = "functions"
  publish = "dist"
  
[[redirects]]
  from = "api/*"
  to = ".netlify/functions/:splat"
  status = 200
  force=true
  query = {path = ":path"}